### ISSUE TITLE
Idee plugin Vip Clasic

### ISSUE THREAD

**Issue by Nodiq** [ShadowsAdi/VIP-Clasic#1]
Daca se poate adauga un cvar ca sa poata numai vipii sa cumpere si sa foloseasca awp si cand cnv care n are vip ia un awp de pe jos il dropeaza automat cvar ca sa pornesti sau opresti asta

**Comment by ShadowsAdi** [comment]
Salut,
Voi face aceasta caracteristica cand voi avea timp liber. Multumesc pentru idee.

**Comment by ShadowsAdi** [comment]
Rezolvat in versiunea 2.0: https://github.com/ShadowsAdi/VIP-Clasic/commit/e449de8e96a95622928ef8d60dfdfc550730cc0c
